name: Build Image
on: 
  push:
    branches: [master]
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jerray/publish-docker-action@v1.0.3
      with:
        username: ${{ secrets.GIT_USER }}
        password: ${{ secrets.GIT_TOKEN }}
        registry: ghcr.io
        repository: 'lg007/hitchcock_server'
        auto_tag: true
